config/routes.rb
Rails.application.routes.draw do
  root  to: 'users#index'
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if params[:image_name]
      @user.image_name = "#{@user.id}.jpg"
      image = params[:image_name]
      File.binwrite("app/assets/images/user_images/#{@user.image_name}", image.read)
    end

    if @user.save
      redirect_to users_url
    else
      render :new
    end
  end
  
  def show
    @user = User.find_by(id: params[:id])
  end

  def edit
  end

  def destroy
    @user = User.find_by(id: params[:id])
    @user.destroy
    redirect_to "/users"
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :image_name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearnCarrierwave</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  </head>

  <body>
    <header>
      <%= link_to('ユーザ一覧', users_url)%>
      <%= link_to('ユーザ作成', new_user_url) %>
    </header>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <% if user.image_name? %>
        <%= image_tag "user_images/#{user.id}.jpg", :size =>'150x150' %>
      <% else %>
        <%= image_tag 'user_images/cat.jpg', :size =>'150x150' %>
      <% end %>
      <h5 class="card-title">名前:<%= user.name %></h5>
      <h6 class="card-subtitle mb-2 text-muted">パスワード:<%= user.password %></h6>
      <%= link_to('編集', edit_user_url(user.id) ,class: "card-link") %>
      <%= link_to('削除', user_url(user.id) ,class: "card-link", method: :delete) %>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <div>
    <p>名前</p>
    <%= f.text_field :name %>
  </div>
  <div>
    <p>パスワード</p>
    <%= f.password_field :password %>
  </div>
  <div>
    <p>アイコン設定</p>
    <%= f.file_field :image_name %>
  </div>
　<%= f.submit '作成', class: 'btn btn-primary' %>
<% end %>